// Auto-generated by scripts/generate-gallery.js - Do not edit manually
// Run: node scripts/generate-gallery.js
// Generated: 2026-02-20T02:32:28.497Z
// VFX: 45 images  |  Photography: 119 images

// ─────────────────────────────────────────────────────────────
// Shared interface
// ─────────────────────────────────────────────────────────────

export interface GalleryImage {
  id: string;
  src: string;
  alt: string;
  category: string;
}

// ─────────────────────────────────────────────────────────────
// VFX Gallery
// Source: public/vfx/gallery/[category]/*.webp
// ─────────────────────────────────────────────────────────────

export const vfxGallery: GalleryImage[] = [
  // ── 3D ──────────────────────────────────────────────────────
  { id: "vfx-3d-001", src: "/vfx/gallery/3d/art_mis_01.webp", alt: "Art Mis 01", category: "3D" },
  { id: "vfx-3d-002", src: "/vfx/gallery/3d/art_mis_02.webp", alt: "Art Mis 02", category: "3D" },
  { id: "vfx-3d-003", src: "/vfx/gallery/3d/art_mis_03.webp", alt: "Art Mis 03", category: "3D" },
  { id: "vfx-3d-004", src: "/vfx/gallery/3d/art_mis_04.webp", alt: "Art Mis 04", category: "3D" },
  { id: "vfx-3d-005", src: "/vfx/gallery/3d/art_mis_05.webp", alt: "Art Mis 05", category: "3D" },
  { id: "vfx-3d-006", src: "/vfx/gallery/3d/art_mis_06.webp", alt: "Art Mis 06", category: "3D" },
  // ── Additional ──────────────────────────────────────────────
  { id: "vfx-add-001", src: "/vfx/gallery/additional/graphics_bfgt_01.webp", alt: "Graphics Bfgt 01", category: "Additional" },
  // ── Drawings ────────────────────────────────────────────────
  { id: "vfx-drw-001", src: "/vfx/gallery/drawings/bvfx_brite_01.webp", alt: "Bvfx Brite 01", category: "Drawings" },
  { id: "vfx-drw-002", src: "/vfx/gallery/drawings/draw_buf_01.webp", alt: "Draw Buf 01", category: "Drawings" },
  { id: "vfx-drw-003", src: "/vfx/gallery/drawings/draw_buf_02.webp", alt: "Draw Buf 02", category: "Drawings" },
  { id: "vfx-drw-004", src: "/vfx/gallery/drawings/draw_buf_03.webp", alt: "Draw Buf 03", category: "Drawings" },
  { id: "vfx-drw-005", src: "/vfx/gallery/drawings/draw_buf_04.webp", alt: "Draw Buf 04", category: "Drawings" },
  { id: "vfx-drw-006", src: "/vfx/gallery/drawings/draw_buf_05.webp", alt: "Draw Buf 05", category: "Drawings" },
  { id: "vfx-drw-007", src: "/vfx/gallery/drawings/draw_buf_06.webp", alt: "Draw Buf 06", category: "Drawings" },
  { id: "vfx-drw-008", src: "/vfx/gallery/drawings/elm_alt_01.webp", alt: "Elm Alt 01", category: "Drawings" },
  { id: "vfx-drw-009", src: "/vfx/gallery/drawings/elm_alt_02.webp", alt: "Elm Alt 02", category: "Drawings" },
  { id: "vfx-drw-010", src: "/vfx/gallery/drawings/elm_alt_03.webp", alt: "Elm Alt 03", category: "Drawings" },
  { id: "vfx-drw-011", src: "/vfx/gallery/drawings/elm_alt_04.webp", alt: "Elm Alt 04", category: "Drawings" },
  { id: "vfx-drw-012", src: "/vfx/gallery/drawings/elm_alt_05.webp", alt: "Elm Alt 05", category: "Drawings" },
  { id: "vfx-drw-013", src: "/vfx/gallery/drawings/elm_alt_06.webp", alt: "Elm Alt 06", category: "Drawings" },
  { id: "vfx-drw-014", src: "/vfx/gallery/drawings/elm_alt_07.webp", alt: "Elm Alt 07", category: "Drawings" },
  { id: "vfx-drw-015", src: "/vfx/gallery/drawings/elm_elmer_01.webp", alt: "Elm Elmer 01", category: "Drawings" },
  { id: "vfx-drw-016", src: "/vfx/gallery/drawings/elm_elmer_02.webp", alt: "Elm Elmer 02", category: "Drawings" },
  { id: "vfx-drw-017", src: "/vfx/gallery/drawings/elm_elmer_03.webp", alt: "Elm Elmer 03", category: "Drawings" },
  { id: "vfx-drw-018", src: "/vfx/gallery/drawings/elm_elmer_04.webp", alt: "Elm Elmer 04", category: "Drawings" },
  { id: "vfx-drw-019", src: "/vfx/gallery/drawings/elm_elmer_05.webp", alt: "Elm Elmer 05", category: "Drawings" },
  { id: "vfx-drw-020", src: "/vfx/gallery/drawings/elm_simps_01.webp", alt: "Elm Simps 01", category: "Drawings" },
  { id: "vfx-drw-021", src: "/vfx/gallery/drawings/elm_simps_02.webp", alt: "Elm Simps 02", category: "Drawings" },
  { id: "vfx-drw-022", src: "/vfx/gallery/drawings/fre_marlon_01.webp", alt: "Fre Marlon 01", category: "Drawings" },
  { id: "vfx-drw-023", src: "/vfx/gallery/drawings/midj_poke_01.webp", alt: "Midj Poke 01", category: "Drawings" },
  { id: "vfx-drw-024", src: "/vfx/gallery/drawings/midj_poke_02.webp", alt: "Midj Poke 02", category: "Drawings" },
  { id: "vfx-drw-025", src: "/vfx/gallery/drawings/midj_tmnt_01.webp", alt: "Midj Tmnt 01", category: "Drawings" },
  { id: "vfx-drw-026", src: "/vfx/gallery/drawings/midj_tmnt_02.webp", alt: "Midj Tmnt 02", category: "Drawings" },
  { id: "vfx-drw-027", src: "/vfx/gallery/drawings/midj_tmnt_03.webp", alt: "Midj Tmnt 03", category: "Drawings" },
  { id: "vfx-drw-028", src: "/vfx/gallery/drawings/midj_tmnt_04.webp", alt: "Midj Tmnt 04", category: "Drawings" },
  { id: "vfx-drw-029", src: "/vfx/gallery/drawings/midj_tmnt_05.webp", alt: "Midj Tmnt 05", category: "Drawings" },
  { id: "vfx-drw-030", src: "/vfx/gallery/drawings/prc_alice_01.webp", alt: "Prc Alice 01", category: "Drawings" },
  { id: "vfx-drw-031", src: "/vfx/gallery/drawings/prc_alice_02.webp", alt: "Prc Alice 02", category: "Drawings" },
  { id: "vfx-drw-032", src: "/vfx/gallery/drawings/prc_alice_03.webp", alt: "Prc Alice 03", category: "Drawings" },
  { id: "vfx-drw-033", src: "/vfx/gallery/drawings/prc_alice_04.webp", alt: "Prc Alice 04", category: "Drawings" },
  { id: "vfx-drw-034", src: "/vfx/gallery/drawings/prc_misc_01.webp", alt: "Prc Misc 01", category: "Drawings" },
  { id: "vfx-drw-035", src: "/vfx/gallery/drawings/prc_misc_02.webp", alt: "Prc Misc 02", category: "Drawings" },
  { id: "vfx-drw-036", src: "/vfx/gallery/drawings/prc_misc_03.webp", alt: "Prc Misc 03", category: "Drawings" },
  { id: "vfx-drw-037", src: "/vfx/gallery/drawings/prc_misc_04.webp", alt: "Prc Misc 04", category: "Drawings" },
  { id: "vfx-drw-038", src: "/vfx/gallery/drawings/prc_poke_01.webp", alt: "Prc Poke 01", category: "Drawings" },
];

// ─────────────────────────────────────────────────────────────
// Photography Gallery
// Source: public/photography/[category]/*.webp
// ─────────────────────────────────────────────────────────────

export const photographyGallery: GalleryImage[] = [
  // ── Commute ─────────────────────────────────────────────────
  { id: "ph-com-001", src: "/photography/commute/photo_com_01.webp", alt: "Photo Com 01", category: "Commute" },
  { id: "ph-com-002", src: "/photography/commute/photo_com_02.webp", alt: "Photo Com 02", category: "Commute" },
  { id: "ph-com-003", src: "/photography/commute/photo_com_03.webp", alt: "Photo Com 03", category: "Commute" },
  { id: "ph-com-004", src: "/photography/commute/photo_com_04.webp", alt: "Photo Com 04", category: "Commute" },
  { id: "ph-com-005", src: "/photography/commute/photo_com_05.webp", alt: "Photo Com 05", category: "Commute" },
  { id: "ph-com-006", src: "/photography/commute/photo_com_06.webp", alt: "Photo Com 06", category: "Commute" },
  { id: "ph-com-007", src: "/photography/commute/photo_com_07.webp", alt: "Photo Com 07", category: "Commute" },
  { id: "ph-com-008", src: "/photography/commute/photo_com_08.webp", alt: "Photo Com 08", category: "Commute" },
  { id: "ph-com-009", src: "/photography/commute/photo_com_09.webp", alt: "Photo Com 09", category: "Commute" },
  { id: "ph-com-010", src: "/photography/commute/photo_com_10.webp", alt: "Photo Com 10", category: "Commute" },
  { id: "ph-com-011", src: "/photography/commute/photo_com_11.webp", alt: "Photo Com 11", category: "Commute" },
  { id: "ph-com-012", src: "/photography/commute/photo_com_12.webp", alt: "Photo Com 12", category: "Commute" },
  { id: "ph-com-013", src: "/photography/commute/photo_com_13.webp", alt: "Photo Com 13", category: "Commute" },
  { id: "ph-com-014", src: "/photography/commute/photo_com_14.webp", alt: "Photo Com 14", category: "Commute" },
  { id: "ph-com-015", src: "/photography/commute/photo_com_15.webp", alt: "Photo Com 15", category: "Commute" },
  { id: "ph-com-016", src: "/photography/commute/photo_com_16.webp", alt: "Photo Com 16", category: "Commute" },
  { id: "ph-com-017", src: "/photography/commute/photo_com_17.webp", alt: "Photo Com 17", category: "Commute" },
  { id: "ph-com-018", src: "/photography/commute/photo_com_18.webp", alt: "Photo Com 18", category: "Commute" },
  { id: "ph-com-019", src: "/photography/commute/photo_com_19.webp", alt: "Photo Com 19", category: "Commute" },
  { id: "ph-com-020", src: "/photography/commute/photo_com_20.webp", alt: "Photo Com 20", category: "Commute" },
  { id: "ph-com-021", src: "/photography/commute/photo_com_21.webp", alt: "Photo Com 21", category: "Commute" },
  { id: "ph-com-022", src: "/photography/commute/photo_com_22.webp", alt: "Photo Com 22", category: "Commute" },
  { id: "ph-com-023", src: "/photography/commute/photo_com_23.webp", alt: "Photo Com 23", category: "Commute" },
  { id: "ph-com-024", src: "/photography/commute/photo_com_24.webp", alt: "Photo Com 24", category: "Commute" },
  { id: "ph-com-025", src: "/photography/commute/photo_com_25.webp", alt: "Photo Com 25", category: "Commute" },
  { id: "ph-com-026", src: "/photography/commute/photo_com_26.webp", alt: "Photo Com 26", category: "Commute" },
  { id: "ph-com-027", src: "/photography/commute/photo_com_27.webp", alt: "Photo Com 27", category: "Commute" },
  { id: "ph-com-028", src: "/photography/commute/photo_com_28.webp", alt: "Photo Com 28", category: "Commute" },
  { id: "ph-com-029", src: "/photography/commute/photo_com_29.webp", alt: "Photo Com 29", category: "Commute" },
  // ── Me ──────────────────────────────────────────────────────
  { id: "ph-me-001", src: "/photography/me/photo_me_01.webp", alt: "Photo Me 01", category: "Me" },
  { id: "ph-me-002", src: "/photography/me/photo_me_02.webp", alt: "Photo Me 02", category: "Me" },
  { id: "ph-me-003", src: "/photography/me/photo_me_03.webp", alt: "Photo Me 03", category: "Me" },
  { id: "ph-me-004", src: "/photography/me/photo_me_04.webp", alt: "Photo Me 04", category: "Me" },
  // ── Neighborhood ────────────────────────────────────────────
  { id: "ph-nbr-001", src: "/photography/neighborhood/photo_jeff_01.webp", alt: "Photo Jeff 01", category: "Neighborhood" },
  { id: "ph-nbr-002", src: "/photography/neighborhood/photo_jeff_02.webp", alt: "Photo Jeff 02", category: "Neighborhood" },
  { id: "ph-nbr-003", src: "/photography/neighborhood/photo_jeff_03.webp", alt: "Photo Jeff 03", category: "Neighborhood" },
  { id: "ph-nbr-004", src: "/photography/neighborhood/photo_jeff_04.webp", alt: "Photo Jeff 04", category: "Neighborhood" },
  { id: "ph-nbr-005", src: "/photography/neighborhood/photo_jeff_05.webp", alt: "Photo Jeff 05", category: "Neighborhood" },
  { id: "ph-nbr-006", src: "/photography/neighborhood/photo_jeff_06.webp", alt: "Photo Jeff 06", category: "Neighborhood" },
  { id: "ph-nbr-007", src: "/photography/neighborhood/photo_jeff_07.webp", alt: "Photo Jeff 07", category: "Neighborhood" },
  { id: "ph-nbr-008", src: "/photography/neighborhood/photo_jeff_08.webp", alt: "Photo Jeff 08", category: "Neighborhood" },
  { id: "ph-nbr-009", src: "/photography/neighborhood/photo_jeff_09.webp", alt: "Photo Jeff 09", category: "Neighborhood" },
  { id: "ph-nbr-010", src: "/photography/neighborhood/photo_jeff_10.webp", alt: "Photo Jeff 10", category: "Neighborhood" },
  { id: "ph-nbr-011", src: "/photography/neighborhood/photo_jeff_11.webp", alt: "Photo Jeff 11", category: "Neighborhood" },
  { id: "ph-nbr-012", src: "/photography/neighborhood/photo_jeff_12.webp", alt: "Photo Jeff 12", category: "Neighborhood" },
  { id: "ph-nbr-013", src: "/photography/neighborhood/photo_jeff_13.webp", alt: "Photo Jeff 13", category: "Neighborhood" },
  { id: "ph-nbr-014", src: "/photography/neighborhood/photo_jeff_14.webp", alt: "Photo Jeff 14", category: "Neighborhood" },
  { id: "ph-nbr-015", src: "/photography/neighborhood/photo_jeff_15.webp", alt: "Photo Jeff 15", category: "Neighborhood" },
  { id: "ph-nbr-016", src: "/photography/neighborhood/photo_jeff_16.webp", alt: "Photo Jeff 16", category: "Neighborhood" },
  { id: "ph-nbr-017", src: "/photography/neighborhood/photo_jeff_17.webp", alt: "Photo Jeff 17", category: "Neighborhood" },
  { id: "ph-nbr-018", src: "/photography/neighborhood/photo_jeff_18.webp", alt: "Photo Jeff 18", category: "Neighborhood" },
  { id: "ph-nbr-019", src: "/photography/neighborhood/photo_jeff_19.webp", alt: "Photo Jeff 19", category: "Neighborhood" },
  { id: "ph-nbr-020", src: "/photography/neighborhood/photo_jeff_20.webp", alt: "Photo Jeff 20", category: "Neighborhood" },
  { id: "ph-nbr-021", src: "/photography/neighborhood/photo_jeff_21.webp", alt: "Photo Jeff 21", category: "Neighborhood" },
  { id: "ph-nbr-022", src: "/photography/neighborhood/photo_jeff_22.webp", alt: "Photo Jeff 22", category: "Neighborhood" },
  { id: "ph-nbr-023", src: "/photography/neighborhood/photo_jeff_23.webp", alt: "Photo Jeff 23", category: "Neighborhood" },
  { id: "ph-nbr-024", src: "/photography/neighborhood/photo_jeff_24.webp", alt: "Photo Jeff 24", category: "Neighborhood" },
  { id: "ph-nbr-025", src: "/photography/neighborhood/photo_jeff_25.webp", alt: "Photo Jeff 25", category: "Neighborhood" },
  { id: "ph-nbr-026", src: "/photography/neighborhood/photo_jeff_26.webp", alt: "Photo Jeff 26", category: "Neighborhood" },
  { id: "ph-nbr-027", src: "/photography/neighborhood/photo_jeff_27.webp", alt: "Photo Jeff 27", category: "Neighborhood" },
  { id: "ph-nbr-028", src: "/photography/neighborhood/photo_jeff_28.webp", alt: "Photo Jeff 28", category: "Neighborhood" },
  { id: "ph-nbr-029", src: "/photography/neighborhood/photo_jeff_29.webp", alt: "Photo Jeff 29", category: "Neighborhood" },
  { id: "ph-nbr-030", src: "/photography/neighborhood/photo_jeff_30.webp", alt: "Photo Jeff 30", category: "Neighborhood" },
  { id: "ph-nbr-031", src: "/photography/neighborhood/photo_jeff_31.webp", alt: "Photo Jeff 31", category: "Neighborhood" },
  { id: "ph-nbr-032", src: "/photography/neighborhood/photo_jeff_32.webp", alt: "Photo Jeff 32", category: "Neighborhood" },
  { id: "ph-nbr-033", src: "/photography/neighborhood/photo_jeff_33.webp", alt: "Photo Jeff 33", category: "Neighborhood" },
  { id: "ph-nbr-034", src: "/photography/neighborhood/photo_jeff_34.webp", alt: "Photo Jeff 34", category: "Neighborhood" },
  { id: "ph-nbr-035", src: "/photography/neighborhood/photo_jeff_35.webp", alt: "Photo Jeff 35", category: "Neighborhood" },
  { id: "ph-nbr-036", src: "/photography/neighborhood/photo_jeff_36.webp", alt: "Photo Jeff 36", category: "Neighborhood" },
  { id: "ph-nbr-037", src: "/photography/neighborhood/photo_jeff_37.webp", alt: "Photo Jeff 37", category: "Neighborhood" },
  { id: "ph-nbr-038", src: "/photography/neighborhood/photo_jeff_38.webp", alt: "Photo Jeff 38", category: "Neighborhood" },
  { id: "ph-nbr-039", src: "/photography/neighborhood/photo_jeff_39.webp", alt: "Photo Jeff 39", category: "Neighborhood" },
  { id: "ph-nbr-040", src: "/photography/neighborhood/photo_jeff_40.webp", alt: "Photo Jeff 40", category: "Neighborhood" },
  { id: "ph-nbr-041", src: "/photography/neighborhood/photo_jeff_41.webp", alt: "Photo Jeff 41", category: "Neighborhood" },
  { id: "ph-nbr-042", src: "/photography/neighborhood/photo_jeff_42.webp", alt: "Photo Jeff 42", category: "Neighborhood" },
  { id: "ph-nbr-043", src: "/photography/neighborhood/photo_jeff_43.webp", alt: "Photo Jeff 43", category: "Neighborhood" },
  { id: "ph-nbr-044", src: "/photography/neighborhood/photo_jeff_44.webp", alt: "Photo Jeff 44", category: "Neighborhood" },
  { id: "ph-nbr-045", src: "/photography/neighborhood/photo_jeff_45.webp", alt: "Photo Jeff 45", category: "Neighborhood" },
  { id: "ph-nbr-046", src: "/photography/neighborhood/photo_jeff_46.webp", alt: "Photo Jeff 46", category: "Neighborhood" },
  { id: "ph-nbr-047", src: "/photography/neighborhood/photo_jeff_47.webp", alt: "Photo Jeff 47", category: "Neighborhood" },
  { id: "ph-nbr-048", src: "/photography/neighborhood/photo_jeff_48.webp", alt: "Photo Jeff 48", category: "Neighborhood" },
  { id: "ph-nbr-049", src: "/photography/neighborhood/photo_jeff_49.webp", alt: "Photo Jeff 49", category: "Neighborhood" },
  { id: "ph-nbr-050", src: "/photography/neighborhood/photo_jeff_50.webp", alt: "Photo Jeff 50", category: "Neighborhood" },
  { id: "ph-nbr-051", src: "/photography/neighborhood/photo_jeff_51.webp", alt: "Photo Jeff 51", category: "Neighborhood" },
  { id: "ph-nbr-052", src: "/photography/neighborhood/photo_jeff_52.webp", alt: "Photo Jeff 52", category: "Neighborhood" },
  { id: "ph-nbr-053", src: "/photography/neighborhood/photo_jeff_53.webp", alt: "Photo Jeff 53", category: "Neighborhood" },
  // ── Protests ────────────────────────────────────────────────
  { id: "ph-prt-001", src: "/photography/protests/photo_prot_01.webp", alt: "Photo Prot 01", category: "Protests" },
  { id: "ph-prt-002", src: "/photography/protests/photo_prot_018.webp", alt: "Photo Prot 018", category: "Protests" },
  { id: "ph-prt-003", src: "/photography/protests/photo_prot_02.webp", alt: "Photo Prot 02", category: "Protests" },
  { id: "ph-prt-004", src: "/photography/protests/photo_prot_03.webp", alt: "Photo Prot 03", category: "Protests" },
  { id: "ph-prt-005", src: "/photography/protests/photo_prot_04.webp", alt: "Photo Prot 04", category: "Protests" },
  { id: "ph-prt-006", src: "/photography/protests/photo_prot_05.webp", alt: "Photo Prot 05", category: "Protests" },
  { id: "ph-prt-007", src: "/photography/protests/photo_prot_06.webp", alt: "Photo Prot 06", category: "Protests" },
  { id: "ph-prt-008", src: "/photography/protests/photo_prot_07.webp", alt: "Photo Prot 07", category: "Protests" },
  { id: "ph-prt-009", src: "/photography/protests/photo_prot_08.webp", alt: "Photo Prot 08", category: "Protests" },
  { id: "ph-prt-010", src: "/photography/protests/photo_prot_09.webp", alt: "Photo Prot 09", category: "Protests" },
  { id: "ph-prt-011", src: "/photography/protests/photo_prot_10.webp", alt: "Photo Prot 10", category: "Protests" },
  { id: "ph-prt-012", src: "/photography/protests/photo_prot_11.webp", alt: "Photo Prot 11", category: "Protests" },
  { id: "ph-prt-013", src: "/photography/protests/photo_prot_12.webp", alt: "Photo Prot 12", category: "Protests" },
  { id: "ph-prt-014", src: "/photography/protests/photo_prot_13.webp", alt: "Photo Prot 13", category: "Protests" },
  { id: "ph-prt-015", src: "/photography/protests/photo_prot_14.webp", alt: "Photo Prot 14", category: "Protests" },
  { id: "ph-prt-016", src: "/photography/protests/photo_prot_15.webp", alt: "Photo Prot 15", category: "Protests" },
  { id: "ph-prt-017", src: "/photography/protests/photo_prot_16.webp", alt: "Photo Prot 16", category: "Protests" },
  { id: "ph-prt-018", src: "/photography/protests/photo_prot_17.webp", alt: "Photo Prot 17", category: "Protests" },
  // ── School ──────────────────────────────────────────────────
  { id: "ph-sch-001", src: "/photography/school/photo_sch_01.webp", alt: "Photo Sch 01", category: "School" },
  { id: "ph-sch-002", src: "/photography/school/photo_sch_02.webp", alt: "Photo Sch 02", category: "School" },
  { id: "ph-sch-003", src: "/photography/school/photo_sch_03.webp", alt: "Photo Sch 03", category: "School" },
  { id: "ph-sch-004", src: "/photography/school/photo_sch_04.webp", alt: "Photo Sch 04", category: "School" },
  { id: "ph-sch-005", src: "/photography/school/photo_sch_05.webp", alt: "Photo Sch 05", category: "School" },
  { id: "ph-sch-006", src: "/photography/school/photo_sch_06.webp", alt: "Photo Sch 06", category: "School" },
  { id: "ph-sch-007", src: "/photography/school/photo_sch_07.webp", alt: "Photo Sch 07", category: "School" },
  { id: "ph-sch-008", src: "/photography/school/photo_sch_08.webp", alt: "Photo Sch 08", category: "School" },
  { id: "ph-sch-009", src: "/photography/school/photo_sch_09.webp", alt: "Photo Sch 09", category: "School" },
  { id: "ph-sch-010", src: "/photography/school/photo_sch_10.webp", alt: "Photo Sch 10", category: "School" },
  { id: "ph-sch-011", src: "/photography/school/photo_sch_11.webp", alt: "Photo Sch 11", category: "School" },
  { id: "ph-sch-012", src: "/photography/school/photo_sch_12.webp", alt: "Photo Sch 12", category: "School" },
  { id: "ph-sch-013", src: "/photography/school/photo_sch_13.webp", alt: "Photo Sch 13", category: "School" },
  { id: "ph-sch-014", src: "/photography/school/photo_sch_14.webp", alt: "Photo Sch 14", category: "School" },
  { id: "ph-sch-015", src: "/photography/school/photo_sch_15.webp", alt: "Photo Sch 15", category: "School" },
];

// ─────────────────────────────────────────────────────────────
// Category lists for filter UI  ('All' is always first)
// ─────────────────────────────────────────────────────────────

export const vfxGalleryCategories = ["All","3D","Additional","Drawings"] as const;

export const photographyCategories = ["All","Commute","Me","Neighborhood","Protests","School"] as const;

// Combined
export const allGalleryImages: GalleryImage[] = [...vfxGallery, ...photographyGallery];
